{% set name = "nemspy" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nemspy-{{ version }}.tar.gz
  sha256: 582ad762b295e35dd6ff7d98d957dd2fa55462a841a74b9f9cafb9288958de14

build:
  noarch: python
  script_env:
    - __version__={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - dunamai
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - nemspy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/noaa-ocs-modeling/nemspy.git
  summary: NEMS configuration generation
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zacharyburnett
